// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUQJ0ik-oioaZXxZsYRTfkxPfBB_3ZL7k',
    appId: '1:349108951270:web:8337e7f61721fa89314327',
    messagingSenderId: '349108951270',
    projectId: 'news-app-2c03e',
    authDomain: 'news-app-2c03e.firebaseapp.com',
    storageBucket: 'news-app-2c03e.appspot.com',
    measurementId: 'G-HHD8WJ46W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmq2umMb9H_bXXEhBcFkUkIMuR6JAFsE',
    appId: '1:349108951270:android:da87e52574c87b4b314327',
    messagingSenderId: '349108951270',
    projectId: 'news-app-2c03e',
    storageBucket: 'news-app-2c03e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2p1V7tEFCdjgJpw_macJmLRpNnko8gpc',
    appId: '1:349108951270:ios:1526bee706916e39314327',
    messagingSenderId: '349108951270',
    projectId: 'news-app-2c03e',
    storageBucket: 'news-app-2c03e.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2p1V7tEFCdjgJpw_macJmLRpNnko8gpc',
    appId: '1:349108951270:ios:1526bee706916e39314327',
    messagingSenderId: '349108951270',
    projectId: 'news-app-2c03e',
    storageBucket: 'news-app-2c03e.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUQJ0ik-oioaZXxZsYRTfkxPfBB_3ZL7k',
    appId: '1:349108951270:web:2755d376af4e548e314327',
    messagingSenderId: '349108951270',
    projectId: 'news-app-2c03e',
    authDomain: 'news-app-2c03e.firebaseapp.com',
    storageBucket: 'news-app-2c03e.appspot.com',
    measurementId: 'G-0YLRQ25816',
  );
}
